### PR TITLE
fix unicode char encoding over U+10000

### LINKED ISSUE #15: Bug counting messages with emoji
It seems now that emoji are counted as 1 character when they occupy the space of 2 characters when encoded with UTF-16.

Given this statement:
```php
$message = "😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎";
var_dump((new SMSCounter())->count($message));
```

This used to output:
```
{
  +"encoding": "UTF16"
  +"length": 139
  +"per_message": 67
  +"remaining": 62
  +"messages": 3
}
```

but now outputs:
```
{
  +"encoding": "UTF16"
  +"length": 70
  +"per_message": 70
  +"remaining": 0
  +"messages": 1
}
```

It would seem from my limited understanding of SMS character encoding that the former is correct.

Related to #10 and introduced by #14

### PR DESCRIPTION
**Pull request by juliangut**
chars length over U+10000 are not correctly identified

Fixes #15

### CODE REVIEW

File: Tests/SMSCounterTest.php [hunk 1]
```diff
@@ -182,17 +219,17 @@ public function testUnicode()
...
 
         $expected = new \stdClass();
         $expected->encoding = SMSCounter::UTF16;
-        $expected->length = 2;
-        $expected->per_message = 70;
-        $expected->remaining = 68;
-        $expected->messages = 1;
+        $expected->length = 132;
+        $expected->per_message = 67;
+        $expected->remaining = 2;
```
Comment (cmorbitzer) [inline Tests/SMSCounterTest.php]: Not sure if we want to do anything about this, but there's a funny situation here because the emoji are twice as long. We say that two are remaining, but in actuality you can only append 1 more (regular) character and stay within 2 messages. If you type 2 more (or 1 more emoji) then it gets moved to a third segment. The reason for this is that the per-message limit is an odd number, so there's actually 1 character's worth of space unused at the end of the first segment. So the "2 remaining" is actually 1 in the first segment and 1 in the second.

Comment (juliangut) [reply Tests/SMSCounterTest.php]: Well, this is indeed an odd situation

Currently remaining char count are checked against text length as a whole, an improvement could be checking length chunk by chunk and return one of this two options:

* Return only what is left in last chunk, even though it will in the end be strange anyway as _length_ + _remaining_ will not match parts total length `132+1 !== 67*2`
* Return a new value _remaining_last_part_ returning that one single char at the end and leaving _remaining_ as it is

Any other idea?

Comment (cmorbitzer) [reply Tests/SMSCounterTest.php]: If I had to guess about most common use cases and the most intuitive fix, I'd say the first option is better even though the sum will be off. The behavior should be documented, though.

File: SMSCounter.php [hunk 2]
```diff
@@ -244,7 +259,23 @@ private function doCount($text, $supportShiftTables)
...
+                if ($count === $perMessage) {
+                    $count = 0;
+                } elseif ($count > $perMessage) {
+                    $count = 2;
+                }
+
+                $count += $char >= 65536 ? 2 : 1;
+            }
+
+            $remaining = $perMessage - ($count > $perMessage ? 2 : $count);
```
Comment (juliangut) [inline SMSCounter.php]: This will do return remaining chars in last part only of UTF16 encoded messages longer than 67

**Comment by juliangut** [comment]
Hi @cmorbitzer 

I've gone for first option as well adding a notice in the Readme file, please review it to see if it's clear enough, and then we can merge this and release 0.5.2

**Comment by cmorbitzer** [comment]
LGTM 👍
